### PR TITLE
chore: replace secp256k1 to @noble/secp256k1

### LINKED ISSUE #21: Replace secp256k1 with @noble/secp256k1
Thanks for building this :heart:

Was thinking if we could replace the [secp256k1](https://www.npmjs.com/package/secp256k1) package with [@noble/secp256k1](https://www.npmjs.com/package/@noble/secp256k1), which claims to be faster and is very light.

It also has all the methods currently being used except for `publicKeyVerify`
```
ecdh             -> getSharedSecret
publicKeyCreate  -> getPublicKey
privateKeyVerify -> utils.isValidPrivateKey
publicKeyVerify  -> :/

### PR DESCRIPTION
**Pull request by im-adithya**
Replaced the entire library, also was able to make up for the method which wasn't available in @noble/secp256k1

Fixes #21

### CODE REVIEW

**Comment by im-adithya** [comment]
@aaronbarnardsound please review this :)

**Comment by lnbc1QWFyb24** [comment]
Thanks for this @im-adithya and awesome work! I added a couple of commits to format and bump the version as well as changing the target branch to develop. I am going to merge this and will look at publishing a release soon. I am just waiting on another change that I want to get in to the next release as well.

**Review by lnbc1QWFyb24 — APPROVED** [review]
🔥

**Comment by lnbc1QWFyb24** [comment]
Hey @im-adithya it seems like the separate Noble packages (secp256k1) should be upgraded to the noble-curves package. See here: https://github.com/paulmillr/noble-curves#upgrading.

Would you be up for creating a new PR that switches to that instead?

**Comment by im-adithya** [comment]
We don't have any other curves being used in this repository, right? That would increase the size unnecessarily (Unless you plan to expand?)

**Comment by lnbc1QWFyb24** [comment]
Yep there aren't any other curves being used and no plans to use other curves. My reading of that upgrade section was that the curves library included the latest and fastest implementation of secp256k1, but after reading further I am not sure! 
I believe since it is an ESM module all the other modules will not be included in the bundle due to tree shaking so I don't think size will be an issue, but we can just leave it as is for now.

**Pull request merged**
