### PR TITLE
Fix: Add missing file resolutions

### PR DESCRIPTION
**Pull request by lnbc1QWFyb24**
- Adds missing `.js` file resolutions that were missed in #4

### CODE REVIEW

**Comment by escapedcat** [comment]
My expectation was actually that a build process could/should handle this. But if you're ok with this "manual" prcoess, also ok.

**Comment by escapedcat** [comment]
Ah, just saw this:  
https://github.com/aaronbarnardsound/lnmessage/pull/7#issuecomment-1309755426  
Alright, moving on. I'm sure we gonna make this work :)

**Comment by bumi** [comment]
without the webpack conifg our build complains about `types.js` (missing the .js there)

```
ERROR in ./node_modules/lnmessage/dist/messages/PongMessage.js 3:0-39
Module not found: Error: Can't resolve '../types' in '/Users/bumi/src/lightning/lightning-browser-extension/node_modules/lnmessage/dist/messages'
Did you mean 'types.js'?
BREAKING CHANGE: The request '../types' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by escapedcat** [comment]
@bumi trying to tackle this here: 
https://github.com/aaronbarnardsound/lnmessage/pull/9

**Pull request merged**
